### ISSUE TITLE
puppet.js not locating QR code

### ISSUE THREAD

**Issue by spags22** [Wicker25/whatstrapp#2]
puppet.js is not locating the QR Code. The 'alt="Scan me!"' image tag is there and I altered the XPath query in _findQRCode() to look for a 'gif' image instead of a 'png' image since WhatApp appears to now be returning 'gif'. Still no luck.

**Comment by Wicker25** [comment]
@spags22 , can you try with the following XPath `$x('//img[@alt="Scan me!" and starts-with(@src, "data:image/")]')`?
